### ISSUE TITLE
Instructions to use and development

### ISSUE THREAD

**Issue by prabhakar267** [connorholyday/vim-snazzy#1]
Hi, the script looks amazing and I want to use it on my local machine, so can you add following to readme?
 - instructions to run it on a local machine
 - what needs to be done in order to add a new language support.

**Comment by connorholyday** [comment]
Thanks for the feedback, I've got a busy couple of evenings ahead but I'll see about getting installation and contribution instructions added by the end of the week

**Comment by connorholyday** [comment]
New documentation has been added, if anything is unclear, lacking explanation, or needs expanding then feel free to open up a new issue and I'd be happy to help you further :)
