### ISSUE TITLE
Invalid characters showing in vim-airline.

### ISSUE THREAD

**Issue by marr** [connorholyday/vim-snazzy#14]
I believe this plugin is responsible for breaking some vim-airline interactions. When I have it enabled, and I use the ctrl-p plugin, I see many invalid `^` characters in my status bar.

**Comment by connorholyday** [comment]
Should all be fixed now, let me know if this is not the case

Here are some relevant links if anyone is interested in this issue:
- https://github.com/vim-airline/vim-airline/issues/258
- https://stackoverflow.com/questions/7223309/vim-statusline-uses-carret-symbols-for-spaces-how-to-switch-to-spaces

**Comment by marr** [comment]
Thanks Connor. verified its working!
