### ISSUE TITLE
Different colors in tmux

### ISSUE THREAD

**Issue by tim-phillips** [connorholyday/vim-snazzy#18]
`vim-snazzy` works great for me when I open vim directly in iterm2, however when opening vim in iterm2 in a tmux session, it has a weird hue to it.

### Outside tmux (correct):
<img width="500" alt="screen shot 2018-08-09 at 10 43 26 pm" src="https://user-images.githubusercontent.com/3578574/43940701-b21ae8b2-9c25-11e8-97bb-9054ba1a8425.png">

### Inside tmux (incorrect):
<img width="500" alt="screen shot 2018-08-09 at 11 15 52 pm" src="https://user-images.githubusercontent.com/3578574/43941760-2fd36f0a-9c2a-11e8-9cb3-d06907f63702.png">

Does this happen to anyone else?

**Comment by tim-phillips** [comment]
I figured it out.

I had to put the following in my `.tmux.conf` (don't ask me why):

```
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'
```

**Comment by connorholyday** [comment]
@tim-phillips Glad you got it figured it out! Good work
