### ISSUE TITLE
Transparent Background Broken

### ISSUE THREAD

**Issue by duncanam** [connorholyday/vim-snazzy#20]
My .vimrc contains:

` colorscheme snazzy `

 ` let g:SnazzyTransparent = 1`

And $HOME/.vim/colors has snazzy.vim inside it. I have no transparent backround. What did I miss?

**Comment by connorholyday** [comment]
Try splitting it up onto separate lines?
```
colorscheme snazzy
let g:SnazzyTransparent = 1
```

**Comment by duncanam** [comment]
Oops, that was meant to be broken up on separate lines. They are, even with a space, and it doesn't do anything.

**Comment by connorholyday** [comment]
How odd! 

Could you tell me what you are using? (terminal emulator, gui client)
Does this environment have a background color itself? (Transparent snazzy just lets the environment background show through)

If you could share your config with me then I can take a look for you

**Comment by nirewen** [comment]
I'm having the same issue. Even setting `g:SnazzyTransparent` above or below the colorscheme declaration, in my `.vimrc` file, doesn't seem to work.

Yes, my terminal app does have a background color. Tried using [Hyper.app](https://hyper.is) and VSCode's embedded terminal, none of them seems to display the theme's background color as transparent, it keeps using the default one.

**Comment by connorholyday** [comment]
Would you be able to share your `.vimrc` and any other config files you think might be relevant? Anything that'll help me recreate the issue would be great :)

**Comment by nirewen** [comment]
My `.vimrc`:
```vim
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_section_y = ''
let g:SnazzyTransparent = 1

colorscheme snazzy
```
I also use vim-airline
Again, the terminal I'm using is [Hyper.app](https://hyper.is) (also tested in VSCode's terminal)

**Comment by duncanam** [comment]
@connorholyday I apologize for the seriously long delay- I've since changed my setup and had forgotten this issue was open. I hope you both resolve it.

**Comment by connorholyday** [comment]
@duncanam no troubles, have a nice week buddy

@nirewen Here are some screenshots using Hyper.app using your `.vimrc` and also using it with the transparent line taken out. I wonder what else might be happening behind the scenes?

What version of vim are you using? I'm running 8.1

![image](https://user-images.githubusercontent.com/4559119/57067704-a4c24e80-6cc7-11e9-8c6c-33b5b30dc054.png)
![image](https://user-images.githubusercontent.com/4559119/57067720-b0157a00-6cc7-11e9-9708-de2a786e123c.png)

**Comment by nirewen** [comment]
Updated vim to version 8.1 and it worked! Thanks @connorholyday
