### ISSUE TITLE
Could you make the the matching parentheses more bright?

### ISSUE THREAD

**Issue by jktzes** [connorholyday/vim-snazzy#21]
<img width="1152" alt="screen shot 2018-12-21 at 7 50 23 pm 2" src="https://user-images.githubusercontent.com/17117898/50341441-c06b5a80-0559-11e9-9c4b-1ab9b3622ff5.png">

As you can see, it's a bit hard to see them when parentheses are far away from each other. Could you modify the color a bit?

**Comment by connorholyday** [comment]
Are you familiar with using `%` to jump to a matching brace? I'd like to find alternatives to modifying colours if possible, any other suggestions?

Could you provide a more real-life code snippet of where you are finding it difficult to see?

**Comment by jktzes** [comment]
Yes, I am. But I suppose "%" is for better navigation, not intended as a complement for highlighting.

I myself made a small fix by adding a ui-4 background color. I tried to modify the yellow foreground color to green or magenta, and it doesn't always work depending on the geographical distribution of elements with those colors. It seems that either a new foreground color need to be introduced, or background color should be present. 

I just made a pull request if you think it's presentable. I think a trade-off is inevitable in this scenario. As for the real-life example, please check the screenshot attached.
<img width="1280" alt="screen shot 2019-01-06 at 4 39 18 pm" src="https://user-images.githubusercontent.com/17117898/50733953-b4c29980-11d1-11e9-9360-88974a713536.png">

**Comment by jktzes** [comment]
Just in case you need a preview of my proposed edit. Here it is.
<img width="1280" alt="screen shot 2019-01-06 at 4 48 46 pm" src="https://user-images.githubusercontent.com/17117898/50734026-00c20e00-11d3-11e9-9456-25558a6a1d07.png">

**Comment by connorholyday** [comment]
I see what you mean now, thanks for providing an example. The proposed edit looks great, I'll check out your PR 👍
