### ISSUE TITLE
`set termguicolors` causes wrong colors inside tmux

### ISSUE THREAD

**Issue by avivace** [connorholyday/vim-snazzy#25]
https://github.com/vim/vim/issues/3608 and a milion other threads on this

**Comment by connorholyday** [comment]
Looks like a nice small fix, are you able to test that this works? I don't use tmux personally so it would be great if you could check it out and put a PR in

**Comment by avivace** [comment]
I'm not sure why it's even needed, in the first place. Removing it fixes the vim theme, but not the lightline one, which keeps showing the wrong colors, when executed inside a tmux session.

I guess we should first figure out the lightline theme issue

**Comment by connorholyday** [comment]
~Looks like lightline [doesn't yet support termguicolors](https://github.com/edkolev/tmuxline.vim/pull/109)~

**Comment by avivace** [comment]
What are you talking about? You linked an issue on "tmuxline.vim", which seems to be something to use unified colors on tmux/lightline/powerline/

**Comment by connorholyday** [comment]
Oh wow what a blunder, apologies for my mistake. Looks like I need another coffee... What does your lightline theme render as?

**Comment by avivace** [comment]
![image](https://user-images.githubusercontent.com/14352721/69725827-64bd3000-111f-11ea-8855-58cd1a4b81cf.png)

**Comment by avivace** [comment]
Okay, I should have fixed it. recent versions of tmux do support truecolor and therefore "set termguicolor" works and doesn't mess anymore with the theme colors.

for reference:
https://github.com/tmux/tmux/issues/696
https://stackoverflow.com/questions/10158508/lose-vim-colorscheme-in-tmux-mode
https://github.com/neovim/neovim/issues/6096
https://www.reddit.com/r/vim/comments/5416d0/true_colors_in_vim_under_tmux/d7z2qr7/

**Comment by connorholyday** [comment]
Thanks for including the references, that'll help anyone else with this issue in future
