### ISSUE TITLE
Looking to make the background a little darker

### ISSUE THREAD

**Issue by rr0ss0rr** [connorholyday/vim-snazzy#28]
I was looking at snazzy.vim and can't figure out how to make the background lean more towards black.  Currently, it seems grey and looking to get a little more contrast.  Thanks

**Comment by connorholyday** [comment]
If you fork or clone the project then you'll be able to change some of the values. The file you'll want to edit is found in `colors/snazzy.vim` and we're using variables for everything.

At the bottom of the file you'll see a section that we use to optionally set the background to transparent. You could use that block of code to instead set all of those sections to have a `guibg` of black.

Does that make sense?

**Comment by rr0ss0rr** [comment]
Thanks for the reply … I tried the following but it did not make any difference .. Using iTerm2 and MacVim

if g:SnazzyTransparent == 1
    highlight  Normal              guibg=black   ctermbg=NONE
    highlight  SignColumn          guibg=black   ctermbg=NONE
    highlight  DiffAdd             guibg=black   ctermbg=NONE
    highlight  DiffDelete          guibg=black   ctermbg=NONE
    highlight  DiffChange          guibg=black   ctermbg=NONE
    highlight  SignifyLineDelete   guibg=black   ctermbg=NONE
    highlight  SignifyLineChange   guibg=black   ctermbg=NONE
endif


-- 
Richard 

A clever person can solve a problem • A wise person will avoid creating the problem   •• Einstein ••

**Comment by rr0ss0rr** [comment]
Got it .. I had to set the option for transparency … Black is too dark.  I have set iterm bg to
rgb hex = 101215 … not sure if that is equivalent to the setting in snazzy … What would I have to do to
set a color to this value?

-- 
Richard 

A clever person can solve a problem • A wise person will avoid creating the problem   •• Einstein ••

**Comment by connorholyday** [comment]
You should be able to use hex codes instead of the black keyword from your example above

**Comment by rr0ss0rr** [comment]
Thanks .. Worked great … one other question … I tried to activate g:SnazzyTransparent in my .vimrc with the following (which did not work)

Let g:SnazzyTransparent = 1

I ended up with changing the if in snazzy.vim… if g:SnazzyTransparent == 0

Thanks again for you help

-- 
Richard 

A clever person can solve a problem • A wise person will avoid creating the problem   •• Einstein ••

**Comment by connorholyday** [comment]
Because you're doing these updates on your own version then you can remove the condition altogether :) glad you got it working, well done!
