### ISSUE TITLE
back ground color is light green in Putty

### ISSUE THREAD

**Issue by yinduren** [connorholyday/vim-snazzy#29]
When I use this color schema in putty, the VIM back ground color is light green.
My putty's name is "putty_V0.63.0.0.43510830.exe"

![image](https://user-images.githubusercontent.com/4429509/85965627-d6c86100-b9ef-11ea-85a7-4c0451cd15b0.png)

**Comment by connorholyday** [comment]
Wow that's messed up. I've not used Putty before and I don't have the time to look into this right now, sorry. Feel free to investigate and open a pull request if that sounds like something you might be interested in doing

**Comment by yinduren** [comment]
I have tried another version of putty. It works well. Likely it happens only on some specific version of putty. So please forget this issue.

**Comment by connorholyday** [comment]
Thanks for reporting anyway 👍
