### ISSUE TITLE
Entire Colorscheme broke

### ISSUE THREAD

**Issue by Soooda** [connorholyday/vim-snazzy#30]
Hello,
I've used this colour scheme in vim for quite a while, however, recently I am trying to move from Vim to NeoVim. I basically copy and paste my entire .vimrc to the init.vim, but I got this weird result.
When I open my init.vim using **vim** everything looks just fine:
<img width="507" alt="Screen Shot 2020-08-30 at 8 54 48 PM" src="https://user-images.githubusercontent.com/27431435/91659581-32ec5600-eb03-11ea-97c0-a2b903fb153f.png">
But if I open it with **nvim**, the entire scheme just broke somehow nor did the background transparency work as well:
<img width="702" alt="Screen Shot 2020-08-30 at 8 56 50 PM" src="https://user-images.githubusercontent.com/27431435/91659607-5c0ce680-eb03-11ea-9539-4c3e19a97afc.png">
Btw, here are the versions for both vim and nvim:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 15 2020 21:59:18)
Included patches: 1-503, 505-680, 682-1283, 1365
Compiled by root@apple.com

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

I am using the MacOS original terminal, and I also found similar behaviour on WSL terminals.

**Comment by connorholyday** [comment]
Curious, which terminal are you using?

**Comment by Soooda** [comment]
> Curious, which terminal are you using?

I am using MacOS's original terminal mostly, but I also discovered similar behavior on my windows machine running WSL on Cmder. Btw, I tried to run the same setup on Iterm2 and everything went fine, so I am assuming it has something to do with the availability of the colors. While it is just weird that I can have vim working and nvim not working on exactly the same terminal xD

**Comment by connorholyday** [comment]
Yes it sounds like colour support to me. Glad it's working on Iterm2 for you though :)

**Comment by Soooda** [comment]
Cheers, m8. Should I close this issue? Coz interpret this issue in another way is like MacOS terminal provides correct colour support for **snazzy** in Vim but NeoVim. At least we concluded a solution to this issue tho. xD

**Comment by connorholyday** [comment]
Sounds good to me. This can always be re-opened if people disagree 👍
