### ISSUE TITLE
Request: Add corresponding bat color theme

### ISSUE THREAD

**Issue by jtrees** [connorholyday/vim-snazzy#31]
I am using [bat](https://github.com/sharkdp/bat) for syntax highlighting in [fzf.vim](https://github.com/junegunn/fzf.vim). Bat provides the ability to choose themes and even comes with a "Sublime Snazzy" theme out-of-the-box. Unfortunately the highlighting from this theme differs to the highlighting provided by vim-snazzy.

It would be cool to have [a bat color theme](https://github.com/sharkdp/bat#adding-new-themes) that matches the vim-snazzy style. Are you up for adding this?

**Comment by connorholyday** [comment]
Unfortunately not! I do think bat is great though. It doesn't sound like it would be too hard if you wanted to take a crack at it yourself :)
