### ISSUE TITLE
How to cancel the background color?

### ISSUE THREAD

**Issue by Free-Ma** [connorholyday/vim-snazzy#33]
### My environment：

- archlinux
- kde

### What do i want to do?
Since my terminal is transparent, I want my vim to be transparent with the terminal, but I don’t know where to modify it

**Comment by sonjiku** [comment]
Hey,

After you set your colorscheme on your vim config, you should run this command some way: `hi Normal guibg=0 ctermbg=0`.

That should set the background color to the one of the terminal. This means same opacity as well.
