### ISSUE TITLE
colorscheme isn't loading

### ISSUE THREAD

**Issue by WVoss31** [connorholyday/vim-snazzy#34]
I first tried to install it manually, and created a `colors` folder in my `.vim` folder, and the entire display in vim is white (including lightline), but when I remove the `colorscheme snazzy` from my vimrc the lightline theme works. I tried installing it with pathogen and vim-plug, but same issue. (transparency works, so I know its reading the file). Below is my vimrc.

```
  1 execute pathogen#infect()
  2
  3 let g:lightline = {
  4     \ 'colorscheme': 'snazzy',
  5     \}
  6 set laststatus=2
  7 set noshowmode
  8
  9 let g:SnazzyTramsparent = 1
 10
 11 let g:SuperTabCompletionContexts = ['s:ContextText', 's:ContextDiscover']
 12 let g:SuperTabContextTextOmniPrecedence = ['&omnifunc', '&completefunc']
 13 let g:SuperTabContextDiscoverDiscovery =
 14     \ ["&completefunc:<c-x><c-u>", "&omnifunc:<c-x><c-o>"]
 15
 16 nnoremap <C-t> : hi Normal guibg=NONE ctermbg=NONE<CR>
 17
 18 set tabstop=4
 19
 20 set number
```

**Comment by WVoss31** [comment]
it's not letting me commit an edit to fix the formatting, sorry

**Comment by connorholyday** [comment]
Looks like you have a typo on line 9
`let g:SnazzyTramsparent = 1` should be `let g:SnazzyTransparent = 1`
