### ISSUE TITLE
Background colorscheme missing background 

### ISSUE THREAD

**Issue by LasseHaslev** [connorholyday/vim-snazzy#8]
The commit [Remove normal background colour to inherit from terminal](https://github.com/connorholyday/vim-snazzy/commit/e03e1ecec2542767b938fb26ea866545846b638e) breaks the colorscheme for me:
![image](https://user-images.githubusercontent.com/3670799/39289049-d1710ea6-492a-11e8-84ce-253f9acd314b.png)
Left is MacVim and right is iterm2, both are missing the background.

Reverting this back fixes it.

**Comment by connorholyday** [comment]
Darn, okay. I'll revert that commit for now and raise a separate issue for what that commit was fixing
